name: Update every hour

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update splat and dependencies
        run: |
          nix run .#update-splat
      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff --quiet || git diff && echo changes=true >> "$GITHUB_OUTPUT"
      - name: Check changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          nix flake check
      - name: Push changes
        if: steps.git-check.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
